version: '3.8'

networks:
  network-postgresql:
    driver: bridge
    name: network-postgresql

volumes:
  volume-postgresql:
    name: volume-postgresql

services:
  postgresql:
    container_name: postgresql
    image: postgres:15.1-alpine
    networks:
      - network-postgresql
    ports:
      - 5432:5432
    volumes:
      - volume-postgresql:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: ${POSTGRE_PWD}
  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4:6.17
    networks:
      - network-postgresql
    ports:
      - 8080:80
    depends_on:
      - postgresql
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PWD}